rust: Fix building of unit-wasm and rust examples
When building the rust stuff we were getting the following compiler
error

  error: failed to run `rustc` to learn about target-specific information

  ...

    --- stderr
    error: Error loading target specification: Could not find specification for target "wasm32-wasi". Run `rustc --print target-list` for a list of built-in targets

This is due to wasm32-wasi being renamed to wasm32-wasip1, with
wasm32-wasi being kept clear for an eventual WASI 1.0 release.

Signed-off-by: Andrew Clayton <a.clayton@nginx.com>